!
! fastSwan configuration saved from vty
!   2026/04/30 00:00:00
!
hostname fastSwan
!
bpf-program xdp-xfrm
 path /etc/fastswan/xfrm_offload.bpf
 no shutdown
!
interface p0
 bpf-program xdp-xfrm
! hairpin-to-nexthop 10.0.0.1
 no shutdown
!
interface p0.502
 no shutdown
!
interface p1
 bpf-program xdp-xfrm
 no shutdown
!
interface p1.504
 no shutdown
!
load-existing-xfrm-policy
!
line vty
 no login
 listen unix owner fswan group fswan
! listen 127.0.0.1 1664
!
