site_name: fastSwan
copyright: Copyright &copy; 2025 Alexandre Cassen
repo_url: https://github.com/acassen/fastswan
repo_name: fastSwan
theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs
    - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
extra:
  homepage: https://www.fastswan.org
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
